### ISSUE TITLE
Awesome tool! Request: output network-id's when outputting as json

### ISSUE THREAD

**Issue by haakonstorm** [laduke/zerotier-central-cli#6]
Awesome tool, thanks for releasing this!

During testing, I'm using `ztc` to list out all the Network ID's. This works in table mode. Then I actually went here to check out whether json output was on the list, and re-read the docs. I do think `-j | --json` is a bit buried in the documentation; perhaps it should be promoted to sort of a "global flag" and viewable just by calling `ztc`?

Anyways, this:
```
ztc network:list --extended --no-truncate --columns="Network-ID" --json | jq '.[]?.description'
```
actually do not result (at least in my account) in a list of the Network IDs. (This is identical output: `ztc network:list --json|jq '.[]?.description'`)

Perhaps an issue on my part, which some of the networks having whitespace / being *null* or otherwise?

Perhaps it could be cool to have autocompletion on the network *friendly names*? With 20+ networks, remembering hashes takes a while to get used to. 🤪

Have a great day brohim. Big ups.

**Comment by haakonstorm** [comment]
(This somewhat dumps the cumulative list:)

```
for nw in $(ztc network:list|sed -n '1!p'|awk '{print $1}'); do export nw; ztc member:list $nw | sed '1,1d; $d'; done | fzf --multi
```

**Comment by laduke** [comment]
hey thanks. This was all slammed together in a short time so there are lots of inconsistencies. If I remember right, many of the flags are just  https://github.com/oclif/oclif defaults or suggestions

I think if you use --json, it just gives you all the json and ignores all those other flags

if you do like 

`ztc network:list --columns="network-id,name,description"`

Does that give you what you want? 

How about 
`ztc network:list --columns="network-id,name,description"  --csv | column -t -s,` haha

or
`ztc network:list -c network-id | xargs -n1 ztc member:list`

something with the friendly names would be great. Or some way to not have to deal with memorizing network IDs. 

I've found myself not reaching for this tool and just going to the website... so it's too hard to use. 
I was thinking maybe make a ncurses style ui

**Comment by haakonstorm** [comment]
No no, your tools is awesome as it is! 
I agree a TUI would be nice -- but not at the expense of dropping CLI support (IMHO).

How about turning it on the head and thinking use-case wise; streamlined for most used tasks? 

E.g. I have a bunch of different ZT networks, and from the top of my head, when I most often *either* reach for `ztc` *or* need to log on to their webui:

1. I want to ssh/vnc a remote box. *What was the Zerotier IP to that box again?* Instead of using the website or keeping a static list of dynamic data, I reach for `ztc`. 

2. Before #1 is possible, "polling" to see when another user has managed to join a network and can be ALLOWed.

3. When in a box in multiple networks: what was the ZT Network ID corresponding to a particular ZT ID. 

4. (Over at the webui, I usually either have to log on to a) allow/deny/kick a member, or b) add a "friendly name" + perhaps a "description" to a member.

And all this can be summed up with dumping a list to e.g. `fzf`; features that would be needed to be added or simplified would be allow/deny member and read/write friendlyname and description.

But, I'm not sure if my main thing was properly explained: there is a bug when exporting JSON. The network IDs aren't exported. Can you verify?


This can be summed up with

- LIST all members in all networks, their IP, online status, and friendly name. (Is it somehow possible to determine if two members of two networks are in fact the same user/virtual nic?
- ALLOW/DENY a member
-

**Comment by laduke** [comment]
> But, I'm not sure if my main thing was properly explained: there is a bug when exporting JSON. The network IDs aren't exported. Can you verify?

ohhhh, that's really weird. how did that happen? i should fix that. 

----

Thanks for the use case info, that gives me some ideas.

**Comment by haakonstorm** [comment]
<img width="506" alt="Screenshot of iTerm2 (04-02-2021, 13-03-15)" src="https://user-images.githubusercontent.com/193781/106890261-5b4b3280-66e9-11eb-90ec-21f683c54693.png">

**Comment by laduke** [comment]
published a new quick version. There should be and 'id' field in the networks list json. 

Is this close to what you're looking for? 
`ztc network:list -c network-id --no-header | xargs -n1 ztc member:list -c="network-id,node-id,authorized" --no-header`

**Comment by haakonstorm** [comment]
Install 'gron' first (via homebrew) and test this one-liner 🤣 slow, but works

```zsh
ztc network:list --json | \
jq -rM '.[]?.id' | xargs -n1 -J% ztc member:list % --json | \
jq -srM '.[] | map(select(.name and .physicalAddress and .config.ipAssignments[0] and .networkId and .nodeId )) | .[] | "[\(.physicalAddress)] \"\(.name)\" \(.networkId) \(.nodeId) = \(.config.ipAssignments[0])"' | \
sort | \
fzf --sort --header='[EXT.ERN.AL.IP] "FRIENDLY NAME" NETWORK-ID NODE-ID = ZER.OTI.ER.IP' --preview='nw={3};node={4};printf "λ ztc get:node %s %s | gron . . .\n\n" "$nw" "$node";ztc member:get --json $nw $node|gron'
```

<img width="754" alt="Screenshot of iTerm2 (12-02-2021, 18-43-26)" src="https://user-images.githubusercontent.com/193781/107802893-32b6de80-6d62-11eb-98cf-fb272b6c9ee7.png">

<img width="1095" alt="Screenshot of Snagit 2021 (12-02-2021, 18-46-34)" src="https://user-images.githubusercontent.com/193781/107803252-a48f2800-6d62-11eb-9c00-6a2ca4467469.png">

**Comment by laduke** [comment]
thanks for the gron tip. I recently found `ijq` which seems also to be helpful. 
closing since I think we resolve the ID thing, but keep commenting or open an issue any time.

**Comment by haakonstorm** [comment]
Wow, thank you again for this; `ijq` is going to prove very useful!
